name: Checking

on: push

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 3
    strategy:
      matrix:
        deno:
          - ~2.4
          - ^2.5

    steps:
      - name: Setup repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Deno
        uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
        with:
          deno-version: ${{ matrix.deno }}

      - name: Run lint
        run: deno lint ./src

      - name: Run publish --dry-run
        run: deno publish --dry-run

      - name: Run tests
        run: deno task test --parallel --coverage --quiet

