name: Checking

on: push

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-slim
    timeout-minutes: 3
    strategy:
      matrix:
        deno:
          - ~2.4
          - ^2.5

    steps:
      - name: Setup repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Deno
        uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          deno-version: ${{ matrix.deno }}

      - name: Run lint
        run: deno lint ./src

      - name: Run publish --dry-run
        run: deno publish --dry-run

      - name: Run tests
        run: deno task test --parallel --coverage --quiet

