name: Checking

on: push

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Deno
        uses: denoland/setup-deno@909cc5acb0fdd60627fb858598759246509fa755 # v2.0.2
        with:
          deno-version: v2

      - name: Run lint
        run: deno lint ./src

      - name: Run publish --dry-run
        run: deno publish --dry-run

      - name: Run tests
        run: |-
          deno task test --parallel --coverage --quiet
          deno coverage --include=./src

