name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
      - stage-*

permissions:
  contents: read
  id-token: write

jobs:
  deploy-cf:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          deno-version: v2

      - name: Test
        run: deno task test

      - name: Build
        run: deno task build

      - name: Artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: ./dist
          name: sri-shasum-${{ github.sha }}
          retention-days: 60

      - name: Deploy
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0.0
        with:
          wranglerVersion: "4.x"
          apiToken:  ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./dist --project-name sri-shasum

